name: Matrix example

on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-20.04]
        node: [18, 20
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install packages
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
