name: Read environment variable
on:
  push:
    branches:
      - feat/env-test
jobs:
  read-env:
    runs-on: ubuntu-latest
    env:
      APP_MODE: ${{vars.APP_MODE}}
    steps:
      - name: Read environment variable
        run: echo "The value of APP_MODE is $APP_MODE"

